### PR TITLE
Adding the display:inline style to Browser Options.

### PR DESCRIPTION
**Pull request by gregoriokusowski**
I'm working on a project that have `img { display: block; }` on its stylesheet.

I don't know how useful this can be, and if the `display:block;` practice is a common one for img's, but this way the I can extract that style from the the project's own css.

Before:
image

After:
image

### CODE REVIEW

**Comment by mkxml** [comment]
As Travis passed and my visual tests in different browsers too I'm going to merge this. The change take effect for people that are using `display:block;` in all images as you are doing, so it is a great addition to the project.

It will help prevent misplaced browser icons as you proved in your first image.

**Comment by mkxml** [comment]
Thanks a lot @gregoriokusowski! May I add you to the contributors list?

**Comment by gregoriokusowski** [comment]
Sure!

My work on this project is over. I'll think on some configurable layout improvements.
Thanks for the merge. :+1:

**Comment by mkxml** [comment]
Nice, if you have an idea in the future feel free to fill an issue and let me know.

**Pull request merged**
